### ISSUE TITLE
is android minSdkVersion 21 really required?

### ISSUE THREAD

**Issue by JoaoMosmann** [agoldis/react-native-mlkit-ocr#1]
Looking at the documentation for MLKit, it works with minSdkVersion 16.

But on [build.gradle](https://github.com/agoldis/react-native-mlkit-ocr/blob/main/android/build.gradle#L32) line 32 it's set to 21

**Comment by agoldis** [comment]
Not sure, did it work for you with 16?

**Comment by LupulescuAlexandru** [comment]
It seems to be working fine with minSdkVersion 16. Check out the example app from Google, they have it set to 16 as well [https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/build.gradle](url)
