### ISSUE TITLE
ios example xcode build failed

### ISSUE THREAD

**Issue by lincdh** [agoldis/react-native-mlkit-ocr#10]
Could you please help me what i'm doing wrong? Thanks!

I just downloaded from the example folder and install the packages, pods then built through xcode and got these messages below :

![image](https://user-images.githubusercontent.com/21136244/119322318-b8bebb80-bca7-11eb-899f-95951d517fe2.png)

**Comment by agoldis** [comment]
@lincdh 
I've just built successfully:
`yarn bootstrap`
`yarn example start`
`yarn example ios`

**Comment by lincdh** [comment]
let me try again. thanks
