### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by Kommandat** [agoldis/react-native-mlkit-ocr#12]
I was curious if I could use this in a managed Expo app. I created a simple project [here](https://github.com/Kommandat/mlkit-demo) to test. I get this error after selecting an image. Any advice or is Expo support infeasible?

```
null is not an object (evaluating 'MlkitOcr.detectFromUri')
at node_modules/react-native-mlkit-ocr/src/index.tsx:70:33 in MLKit.detectFromUri
at node_modules/react-native-mlkit-ocr/src/index.tsx:69:17 in MLKit.detectFromUri
at App.js:85:22 in launchGallery
```

**Comment by Noitidart** [comment]
It works with eas build I'm actually working on this as we speak. I got it installed but its not giving me any text, I'm working on seeing if I did something wrong. But I'm pretty sure it installed corectly, its probably just me doing something weird in the api.

Follow these steps to install, you must be using SDK 42 I think for eas:

1. `expo init`
2. `expo install react-native-mlkit-ocr expo-dev-client`
3. `eas build -p all --profile development`
4. When the build completes, go to the build page on expo.io and then tap install, it opens a QR code
5. Scan that QR code with your device, it will download the app to it.
6. Start the download app.
7. From your expo codebase type in `expo start --dev-client`
8. It's installed you should be able to use it

I'll let you know when I get text, right now I got a camera taking a picture and giving me a URI but it's not reading the text I'm probably doing something wrong.

**Comment by Noitidart** [comment]
Oops I thought I posted this, but it's working! I was taking a photo of the Samsung logo which was shiny so it wasn't seeing it. Major thanks to the authors of this lib. I'm using expo-camera, using takePhotoAsync and feeding URI to detectWithUri from this lib and it gives me a nice array of bounding boxes for all the elements with the text in it.

**Comment by Kommandat** [comment]
Got it. It looks like I need to purchase the Expo Priority plan to use EAS. Will do and will share my updates and whether it fixes my issue! Thanks!

**Comment by Noitidart** [comment]
Correct it is a 30$ a month thing but its so worth it. Getting Bitrise just for builds is expensive. And expo gives builds and submission to the store, and it supports them to continue the awesome stuff they've already given for free like notifications and all the api's.

**Comment by Kommandat** [comment]
@Noitidart Thanks for the help. The app works with `eas build`. Quick question, does this mean when developing you need to wait for your expo build to finish in order to test any changes? That's a little annoying, but I guess it's doable.

**Comment by Noitidart** [comment]
No only one time after running `eas build`. You only need to run `eas build` after `npm i`'ing a new native module. After that you can keep using that "custom client". :) It's way awesome.

**Comment by Kommandat** [comment]
Thanks so much @Noitidart! You've made my development experience 10x easier.

And thanks to this library for helping me with my app 👍 

To those new to Expo Custom Development Clients, I found these resources helpful to get started:
- https://www.youtube.com/watch?v=Iw8FAUftJFU
- https://docs.expo.dev/clients/getting-started/

**Comment by Noitidart** [comment]
:)
