### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by Noitidart** [agoldis/react-native-mlkit-ocr#13]
In iOS I'm having issue that if I don't take the photo in landscape it won't read the text.

And on Android I'm having issue of it only working in portrait mode.

Is this an expected thing? Is there a way to hint orientation so I don't have to rotate photo?

**Comment by mlcal** [comment]
@Noitidart  Can you tell me how you rotate image before take a photo ?

**Comment by Noitidart** [comment]
@mlcal I use Expo so I used their `ImageManipulator` class - https://docs.expo.dev/versions/latest/sdk/imagemanipulator/#imagemanipulatormanipulateasyncuri-actions-saveoptions

      Promise.all([
          ImageManipulator.manipulateAsync(photoResponse.uri, [{ rotate: 90 }]),
          ImageManipulator.manipulateAsync(photoResponse.uri, [{ rotate: -90 }]),
          ImageManipulator.manipulateAsync(photoResponse.uri, [{ rotate: 180 }])
      ])
