### ISSUE TITLE
iOS builds not approved by App Store due to unpinned GoogleMLKit/TextRecognition version

### ISSUE THREAD

**Issue by Kommandat** [agoldis/react-native-mlkit-ocr#14]
There was a [thread](https://forums.expo.dev/t/ios-store-submit-fails-due-to-itms-90562-invalid-bundle/56292/15) in the Expo forums on how iOS builds were being rejected by the App store due to the following error:

```
ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again. 
```

*The solution was to pin the GoogleMLKit/TextRecognition pod to version 2.2.0 per Google's release notes [here](GoogleMLKit/TextRecognition pod).* This solves the build issue, but the downside is that it uses MLKit's Text Recognition v1 instead of Text Recognition v2 (in beta).

Currently, I applied this solution in my project project using patch-package, but are we open to pinning the version number to 2.2.0 in the .podspec file here? It's a simple code change and I'd like to make it & contribute if possible.

Thanks!

**Comment by Noitidart** [comment]
@agoldis is pinning the right thing to do? Does it only affect certain react-native versions? Or does it affect all?

I also had this problem by the way.

**Comment by agoldis** [comment]
@Kommandat @Noitidart 
https://developers.google.com/ml-kit/vision/text-recognition/ios and https://developers.google.com/ml-kit/vision/text-recognition/v2/ios both have the version pinned. 
I think letting the app "pass" App store review is preferred by majority of users. One can always patch if needed. If there's an important use case unpin the version we can always revert.

**Comment by Noitidart** [comment]
Got it thanks.
