### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by najeeb2113** [agoldis/react-native-mlkit-ocr#18]
while running yarn example android i get this

Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by blinqwebstudio** [comment]
In case someone gets to this issue; there's no Gradle Wrapper with the example project. 
The accepted answer to this question solves the problem: https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain 
(you need to run `gradle wrapper` inside ./example/android/)
