### ISSUE TITLE
execution MlkitOcr.detectFromFile(path) or MlkitOcr.detectFromFile(path) produce an error

### ISSUE THREAD

**Issue by epoq** [agoldis/react-native-mlkit-ocr#19]
Hello , thanks for your help.
i try to use this library and i have an error when a try to use the principal methods :

const resultFromUri = await MlkitOcr.detectFromUri(uri);
const resultFromFile = await MlkitOcr.detectFromFile(path);

result : ---> error : [TypeError: null is not an object (evaluating 'MlkitOcr.detectFromFile')]

thanks for your help.
i use expo .

**Comment by roysG** [comment]
It looks like it not detect the package
Did you run npm install react-native-mlkit-ocr ??
Did you run build again?

**Comment by agoldis** [comment]
@epoq see https://github.com/agoldis/react-native-mlkit-ocr/tree/main/example for setup example, not clear what's your setup like

**Comment by Maker-Mark** [comment]
@agoldis, thank you for making this package!
There is no example using detectFromFile in this repository, there's only for detectFromUri. 
I'm getting "No image path provided" even though I absolutely am
```
No image path provided
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/react-native-mlkit-ocr/src/index.tsx:76:18 in MLKit.detectFromFile
at node_modules/react-native-mlkit-ocr/src/index.tsx:76:18 in MLKit.detectFromFile

```
