### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by nathanael-anstett** [agoldis/react-native-mlkit-ocr#2]
Hello, I tried to install the package on my react native project (npm install + pod install), but the build is failing. Below is the xCode output :

![image](https://user-images.githubusercontent.com/74770959/114958910-b1caa080-9dff-11eb-9142-ed72626f87e8.png)

What I am missing ? Is there another installation step ?

**Comment by agoldis** [comment]
@nathanael-anstett sorry for delayed response. It's quite hard to troubleshoot the issues based on just that screenshot. 
I double-checked the the package runs smoothly on iOS 14.3 simulator, following the [Example](https://github.com/agoldis/react-native-mlkit-ocr#example) instructions. 


Please let me know if you've had any success.

**Comment by nathanael-anstett** [comment]
My bad... Indeed i must have done something wrong. I uninstalled and reinstalled your package, and after a pod install the build worked fine. Thank you for your quick answer
