### ISSUE TITLE
Build fail with error in ios

### ISSUE THREAD

**Issue by roysG** [agoldis/react-native-mlkit-ocr#21]
CopySwiftLibs /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app (in target 'app' from project 'app')
    cd /Users/roysabah/www/automati/app/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk
    builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app/app --scan-folder /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app/Frameworks --scan-folder /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app/PlugIns --platform iphonesimulator --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app/Frameworks --strip-bitcode --strip-bitcode-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info /Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app.build/SwiftStdLibToolInputDependencies.dep

error: Build input file cannot be found: '/Users/roysabah/Library/Developer/Xcode/DerivedData/app-aebhwuspvfqrccddikslhrdwtozf/Build/Products/Debug-iphonesimulator/app.app/app' (in target 'app' from project 'app')

**Comment by roysG** [comment]
react-native -v:
react-native-cli: 2.0.1
react-native: 0.63.4

**Comment by agoldis** [comment]
Hey @roysG  I can't provide any help based on the data you've published.

**Comment by roysG** [comment]
Please tell me which information you need and i will give you
