### ISSUE TITLE
Recognize text chinese, japanese, korean

### ISSUE THREAD

**Issue by anhnguyen123** [agoldis/react-native-mlkit-ocr#22]
I tried to recognize chinese, japanese, korean but not found, just english text. can you help me to update this repo.

**Comment by agoldis** [comment]
The library uses Google MLKit - please see the list of supported languages:
 
https://developers.google.com/ml-kit/vision/text-recognition/languages

Unfortunately the languages you've mentioned are not supported :(

**Comment by anhnguyen123** [comment]
> The library uses Google MLKit - please see the list of supported languages:
> 
> https://developers.google.com/ml-kit/vision/text-recognition/languages
> 
> Unfortunately the languages you've mentioned are not supported :(

can you update to Text Recognition v2

**Comment by timmyjose** [comment]
@agoldis Any idea how much effort it would be to upgrade to MLKit V2? This library works beautifully well, apart from the Latin-text only restriction!
