### ISSUE TITLE
Question - Do you need to sign up with google firebase to use this?

### ISSUE THREAD

**Issue by cristianoccazinsp** [agoldis/react-native-mlkit-ocr#3]
Just wondering, other camera libraries (e.g., react-native-camera) are also able to use firebase MLKIT, but they always require you to sign up with a google account in firebase.

Does this library work right away without doing so?

Thanks!

**Comment by agoldis** [comment]
> Does this library work right away without doing so?

Yes. 


Please note, it doesn't include any integration with camera - it can read file. You'll need an additional library to capture an image, save it and then provide as an input to this package.
