### ISSUE TITLE
build error on RN 0.69.1 / package incomplete

### ISSUE THREAD

**Issue by Productivix** [agoldis/react-native-mlkit-ocr#32]
when we have added the module on a fresh RN0.69.1 , do a yarn run android and you get the error mainly: 

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
How that module be integrated in a recent fresh react-native init 0.69.1 please ?

**Comment by TheCrowd** [comment]
having the same issue as well. Do you have any solution for this?

**Comment by Productivix** [comment]
hi, 
the previous test  was on a Linux stack compiled on a And 11 terminal . Now I am with windows stack that compiles  (attached config desc) for an And 8 terminal.
[RN0691_Win.txt](https://github.com/agoldis/react-native-mlkit-ocr/files/9102758/RN0691_Win.txt)
I have then in Metro the following error : 
`
 BUNDLE  ./index.js

error: Error: Unable to resolve module react-native-vector-icons/Ionicons from C:\Users\info\Downloads\OCR-app-master\OCR-app-master\App\Navigation\LoggedInStack.js: react-native-vector-icons/Ionicons could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React, {useState, useEffect, useRef} from 'react';
  2 | import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
> 3 | import Ionicons from 'react-native-vector-icons/Ionicons';
    |                       ^
  4 |
  5 | import HomeStack from './HomeStack';
`
that is solved by : 
yarn add react-native-vector-icons
and after line 85 of android/app/build.gradle : 
`project.ext.vectoricons = [
    iconFontNames: [ 'Ionicons.ttf' ] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

then recompile yarn run android, 
and you get another error : 
`
" Error: Unable to resolve module ../Containers/ from C:\Users\info\Downloads\OCR-app-master\OCR-app-master\App\Navigation\NotLoggedInStack.js:

None of these files exist:
  * App\Containers(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * App\Containers\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  3 | import AsyncStorage from '@react-native-async-storage/async-storage';
  4 |
> 5 | import LoginScreen from '../Containers/';
    |                          ^
'
corrected , 
then error : 
` Error: Unable to resolve module ../Containers/Setting from C:\Users\info\Downloads\OCR-app-master\OCR-app-master\App\Navigation\LoggedInStack.js:`

Obviously this package has not been published running or completed !!

**Comment by AbhinayMe** [comment]
> when we have added the module on a fresh RN0.69.1 , do a yarn run android and you get the error mainly:
> 
> Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15. How that module be integrated in a recent fresh react-native init 0.69.1 please ?

I have faced the same issue & resolved by declaring Kotlin version to "1.6.0" in android/build.gradle file
```
ext {
        kotlinVersion="1.6.0"
}
```

**Comment by Productivix** [comment]
hi @AbhinayMe , thank you , that is the solution ! it compiles well now.
