### ISSUE TITLE
I get type errors with RN 70.x

### ISSUE THREAD

**Issue by zirho** [agoldis/react-native-mlkit-ocr#38]
probably not related to the RN itself.
after installing the library, I get type error.

I've found an old issue and tried 0.2.2 but still get the error.
https://github.com/agoldis/react-native-mlkit-ocr/pull/7

I don't see `d.ts` file in any of release.

![image](https://user-images.githubusercontent.com/1251296/204914511-8431b48a-1a9e-4125-a4cf-befae36106a8.png)

**Comment by fahmidyt** [comment]
@agoldis hey, can u merge this and update the package? this will be very helpful. thx
