### ISSUE TITLE
Limit scan to bounding box?

### ISSUE THREAD

**Issue by cristianoccazinsp** [agoldis/react-native-mlkit-ocr#4]
Is it possible (or does the google SDK) support a way to limit the text extraction to a bounding box? Could be useful to speed up the process and reduce the amount of junk when scanning certain things.

I'm up to provide a PR if the google SDK supports that somehow.

**Comment by agoldis** [comment]
Here's API spec to accept images: https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage

I don't see any build-in "bounding box". I'd suggest to manipulate the image first and then process it with the mlkit.

**Comment by cristianoccazinsp** [comment]
My solution was to just map the UI's bounding box (e.g., some random padding from the camera feed), and then filter out blocks where their `cornerPoints` are out of the bounding box.  The bounding box is basically the image dimensions minus the padding (converted to pixels with getPixelSizeForLayoutSize).

Seems to work well enough!
