### ISSUE TITLE
Gradle kotlin issues with other libraries

### ISSUE THREAD

**Issue by cristianoccazinsp** [agoldis/react-native-mlkit-ocr#5]
Hello,

When building for production, I'm getting the following warning/error:

```
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-mlkit-ocr', ':react-native-webview'
```

I also have the following in build.gradle in order for both libraries to use the same version:

```
kotlinVersion="1.4.32"
```

**Comment by agoldis** [comment]
Were you able to solve it?

**Comment by cristianoccazinsp** [comment]
Not really, I'm just ignoring the warning for now as it still seems to compile and bundle fine. But it seems like it may start to become an issue as more libraries upgrade to kotlin. Haven't had enough time to dig into it further.

**Comment by agoldis** [comment]
Not sure how to resolve that - the message suggests to enable Kotlin globally in the root project and remove from the subprojects, but it seems unreasonable, because every individual project needs Kotlin. 

I'd suggest at least to make sure you define the same Kotlin version by adding:
```
ext {
    kotlinVersion = "<version>"
}
```

to your root `android/build.gradle`.

**Comment by cristianoccazinsp** [comment]
I can confirm that `kotlinVersion` is defined, but even the warning itself says that it will be reported even if the versions match `...DSL if they specify explicit versions, even if the versions are equal`

So I don't really know how to handle it. I agree that having to upgrade every sub project would be nonsense.

**Comment by cristianoccazinsp** [comment]
So do you think this should be just ignored as the apps will still build with the warning?  Perhaps until the RN figures out a way to mix kotlin without warnings.

**Comment by agoldis** [comment]
@cristianoccazinsp yep, seems like it's a general issue (or not an issue) with all RN Kotlin-based packages.
