### ISSUE TITLE
iOS armv7 build issues - looking for recommendations

### ISSUE THREAD

**Issue by cristianoccazinsp** [agoldis/react-native-mlkit-ocr#6]
The default XCode template for RN builds for both arm64 and armv7. However, Google's SDK is only available for arm64 (no 32-bit support). This is problematic as the iOS simulator must run with armv7, so limiting the architectures to arm64 prevents you from running the entire project in the simulator (even if the library itself is not used).  

I thought/tried about allowing armv7 and arm64 for debug, and just arm64 for release so final builds do not raise any error, but this causes cocoapods / pod install to fail due to different values for each architecture (which makes sense since pods have to compile/define the architecture for each sub project).

So far, this leaves me with the annoying procedure of switching from arm64 to armv7 + arm64 architecture each time I need to test on a simulator. 

Any ideas how this process could be improved? Thanks.

<img width="742" alt="Screen Shot 2021-05-02 at 12 34 11" src="https://user-images.githubusercontent.com/48869228/116818633-cd91ae80-ab42-11eb-873f-ca67e92e9e72.png">

**Comment by agoldis** [comment]
@cristianoccazinsp Sorry to see those problems, I totally can see how that might be annoying. Saying it back, there's some additional Google's SDK in your app that only compiles to armv64. 

I remember having a similar problem with one of my apps. We ended up doing some scripting on Bitwise to rewire build process - devs used simulators, CI was building for other architectures. Sorry for not being able to help.

**Comment by agoldis** [comment]
👍🏻
